---
title: "Understanding the Comprehensive Mobility Plan for Bengaluru 2020"
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

library(sf)
library(tidyverse)
library(tmap)

tmap_mode("view")

```

```{css, echo=FALSE}

d-title {
  display:none;
}

```

<!-- Use a HTML break to add a little white space between the title and the map -->
<br>

```{r}
# I want the home screen to contain an interactive map of Bangalore which shows all the projects proposed in the Comprehensive Mobility Plan for Bengaluru 2020. The map needs to have relevant boundaries (BBMP Ward, BMRDA) in addition to the projects. Also, projects will need to be categorized to make it easier to understand.

# Now load in the dataset for this map. To start with, its going to have just points.

bangaloreCMPProjects <- readxl::read_xlsx(here::here("data/raw-data/bangaloreCMP2020Projetcs.xlsx"))

# Okay. I tried working with all projects in one DF but its makes sense to split them by project type. Then I can make the pop-up info more useful.

# Filter out the locations that are not geo-located yet

geoRefProjects <- bangaloreCMPProjects %>% 
  filter(!is.na(location)) %>% 
  separate(location, sep = ", ", into = c("lon", "lat"))

# Convert lat and long into geometry

geoRefProjects <- geoRefProjects %>% 
  st_as_sf(coords = c("lat", "lon"), crs = 4326) %>% 
  st_transform(3857)

# Define a Palette

myPalette <- c("#f94144",
               "#f3722c",
               "#f8961e",
               "#f9844a",
               "#f9c74f",
               "#90be6d",
               "#43aa8b",
               "#4d908e",
               "#577590",
               "#277da1")

```

```{r}
# BASE MAP

# The CMP 2020 defines the study area as the whole of Bengaluru Metropolitan Area (1294.00 Sq.Km), part of Bangalore-Mysore Infrastructure Corridor Area (79.14 Sq.Km) and a part of Bangalore International Airport Area Local Planning Authority (227.85 Sq.Km). BUT, I don't see a map which explicitly shows these areas. :/ 

# Till I figure that out, I'll show the BBMP and metropolitan area boundaries.

# First, I will set up a base map with the BBMP ward boundaries.

bangaloreWardBoundary <- read_sf(here::here("data/raw-data/bangaloreWardBoundary.shp"))

bangaloreWards <- readRDS(here::here("data/raw-data/bangaloreWardMap.rds"))

# Transform it for consistency

bangaloreWardBoundary <- bangaloreWardBoundary %>% 
  st_transform(3857)

bangaloreWards <- bangaloreWards %>% 
  st_transform(3857)

# I'll draw the base map here. I want a thicker border for the overall outline of the wards and thinner lines showing individual wards.

mapBase <- tm_shape(bangaloreWardBoundary) +
  tm_borders(col = "#000000",
             lwd = 2) +
  tm_shape(bangaloreWards) +
  tm_borders(col = "#000000",
             lwd = 0.5)

```

```{r}
# JUNCTION IMPROVEMENT PROJECTS

# Filter only the junction improvement projects

junctionImprovement <- geoRefProjects %>% 
  filter(type == "Junction Improvement")

# Rename columns for neater display

junctionImprovement <- junctionImprovement %>%
  select(-description_1, -description_2) %>% 
  rename(ID = "id",
         Type = "type",
         Description = "description_0",
         Budget = "budget")

# Rearrange columns so that I get the type in the pop-up

junctionImprovement <- junctionImprovement %>% 
  select(Type, Description, Budget, ID, geometry)

# Draw Junction Improvement Map

mapJunctionImprovement <- junctionImprovement %>% 
  tm_shape() +
  tm_dots(col = "#f94144",
          popup.vars = c("ID", "Type", "Description", "Budget"))

```

```{r}
# OFF-STREET PARKING PROJECTS

# Filter only the junction improvement projects

offStreetParking <- geoRefProjects %>% 
  filter(type == "Off-Street Parking")

# Rename columns for neater display

offStreetParking <- offStreetParking %>%
  rename(ID = "id",
         Type = "type",
         Description = "description_0",
         Area = "description_1",
         Count = "description_2",
         Budget = "budget")

# Rearrange columns so that I get the type in the pop-up

offStreetParking <- offStreetParking %>% 
  select(Type, Description, ID, Area, Count, Budget, geometry)

# Draw Junction Improvement Map

mapOffStreetParking <- offStreetParking %>% 
  tm_shape() +
  tm_dots(col = "#277da1",
          size = 0.15,
          alpha = 0.5,
          border.alpha = 0,
          popup.vars = c("ID", "Type", "Description", "Area", "Count", "Budget"))

```

```{r}
# STATION AREA ACCESS PLAN PROJECTS

# Filter only the station area access plan projects

stationAreaAccess <- geoRefProjects %>% 
  filter(type == "Station Area Access Plan")

# Rename columns for neater display

stationAreaAccess <- stationAreaAccess %>%
  rename(ID = "id",
         Type = "type",
         Description = "description_0",
         Budget = "budget")

# Rearrange columns so that I get the type in the pop-up

stationAreaAccess <- stationAreaAccess %>% 
  select(Type, Description, ID, Budget, geometry)

# Draw Junction Improvement Map

mapStationAreaAccess <- stationAreaAccess %>% 
  tm_shape() +
  tm_dots(col = "#f8961e",
          popup.vars = c("ID", "Type", "Description", "Budget"))

```

```{r}
# INTER MODAL INTERCHANGE HUB

# Filter only the inter modal interchange hub projects

interModalHubs <- geoRefProjects %>% 
  filter(type == "Inter Modal Interchange Hub")

# Rename columns for neater display

interModalHubs <- interModalHubs %>% 
  rename(ID = "id",
         Type = "type",
         Description = "description_0",
         Interchange = "description_1",
         Budget = "budget")

# Rearrange columns so that I get the type in the pop-up

interModalHubs <- interModalHubs %>% 
  select(Type, Description, ID, Interchange, Budget, geometry)

# Draw interchange hub map

mapInterModalHubs <- interModalHubs %>% 
  tm_shape() +
  tm_dots(col = "#90be6d",
          popup.vars = c("ID", "Type", "Description", "Interchange", "Budget"))

```

```{r, layout="l-screen-inset", fig.height= 6.75}
# Publish combined map

mapBase + mapJunctionImprovement + mapOffStreetParking + mapStationAreaAccess + mapInterModalHubs
```

```{r}
# STAT CALCULATION

# I'd like to display counts about the total number of projects in the CMP and the number of projects that have been geo-referenced. It'll help show that things are still in progress and is also an indicator of the complexity of things.

# Total projects should be a static amount as counted from the CMP


# Georeferenced project count

geoRefCount <- geoRefProjects %>% 
  count() %>% 
  st_set_geometry(NULL) %>% 
  select(n)
```

<center>

### `r geoRefCount` projects have been geo-referenced as of `r format(Sys.Date(), "%d %B, %Y")`

</center>

---

```{r}
# I want a table to display the non-georefed projects

nonGeoRefProjects <- bangaloreCMPProjects %>% 
  filter(is.na(location)) %>% 
  select(-location)

nonGeoRefProjects <- nonGeoRefProjects %>% 
  rename(ID = "id",
         Type = "type",
         Description0 = "description_0",
         Description1 = "description_1",
         Description2 = "description_2",
         Budget = "budget")

# I also want to show the count of non-georefed projects

nonGeoRefCount <- nonGeoRefProjects %>% 
  count() %>% 
  select(n)

```


<center>

### `r nonGeoRefCount` projects are queued for geo-referencing as of `r format(Sys.Date(), "%d %B, %Y")`

</center>

```{r, layout="l-screen-inset", fig.height= 6.75}

rmarkdown::paged_table(nonGeoRefProjects, 
                       options = list(rows.print = 20))
```

